"""removing some tables in my column

Revision ID: dc8a1f382e60
Revises: 4c0912b9332e
Create Date: 2019-07-21 22:38:46.238324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc8a1f382e60'
down_revision = '4c0912b9332e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'image_url')
    op.drop_column('task', 'image_filename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('image_filename', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
